# Generated by Django 4.1 on 2023-08-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plexaccount',
            old_name='thumnail_url',
            new_name='thumbnail_url',
        ),
    ]
