# Generated by Django 4.1 on 2023-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0002_rename_thumnail_url_plexaccount_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plexaccount',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/plex_thumbnails/'),
        ),
    ]
