# Generated by Django 4.1 on 2023-08-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('guid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('alias', models.TextField(blank=True, null=True)),
                ('device_id', models.TextField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('mac', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
            ],
            bases=('home.basemodel',),
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('headers', models.JSONField(default=dict)),
                ('json_data', models.JSONField(default=dict)),
                ('meta_data', models.JSONField(default=dict)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            bases=('home.basemodel',),
        ),
    ]
