# Generated by Django 4.1 on 2023-08-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasaDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.device')),
                ('on_since', models.DateTimeField(blank=True, null=True)),
                ('is_bulb', models.BooleanField(default=False)),
                ('is_color', models.BooleanField(default=False)),
                ('is_dimmable', models.BooleanField(default=False)),
                ('is_dimmer', models.BooleanField(default=False)),
                ('is_light_strip', models.BooleanField(default=False)),
                ('is_off', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('is_plug', models.BooleanField(default=False)),
                ('is_strip', models.BooleanField(default=False)),
                ('is_strip_socket', models.BooleanField(default=False)),
                ('is_variable_color_temp', models.BooleanField(default=False)),
                ('has_emeter', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
            ],
            bases=('home.device',),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('realtime_current_reading', models.FloatField(default=0.0)),
                ('realtime_power_reading', models.FloatField(default=0.0)),
                ('realtime_total_reading', models.FloatField(default=0.0)),
                ('realtime_voltage_reading', models.FloatField(default=0.0)),
                ('day_reading', models.FloatField(default=0.0)),
                ('month_reading', models.FloatField(default=0.0)),
                ('kasa_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.kasadevice')),
            ],
            bases=('home.basemodel',),
        ),
    ]
